###
POST http://localhost:3001/api/v2/superheroes_V2/superhero HTTP/1.1
Content-Type: application/json

{
  "superhero_name": "Flasassdfsd",
  "real_name": "Clark",
  "features": [{
    "universe": "DC",
    "super_powers": ["Be Alien"]
    }],
    "superhero_sidekick": [{
      "sidekick": "Piotr Rasputin",
      "side_powers": ["be metallic"]
    }]
}
